export class Timesheet {
  mondayStartTime:String;
  mondayEndTime:String;
  tuesdayStartTime:String;
  tuesdayEndTime:String;
  wednesdayStartTime:String;
  wednesdayEndTime:String;
  thursdayStartTime:String;
  thursdayEndTime:String;
  fridayStartTime:String;
  fridayEndTime:String;
  saturdayStartTime:String;
  saturdayEndTime:String;
  sundayStartTime:String;
  sundayEndTime:String;
  status:String;
  user:any;
  supervisor:any;
}
