export class Timesheet {
  mondayStartTime:String = "00:00";
  mondayEndTime:String= "00:00";
  tuesdayStartTime:String= "00:00";
  tuesdayEndTime:String= "00:00";
  wednesdayStartTime:String= "00:00";
  wednesdayEndTime:String= "00:00";
  thursdayStartTime:String= "00:00";
  thursdayEndTime:String= "00:00";
  fridayStartTime:String= "00:00";
  fridayEndTime:String= "00:00";
  saturdayStartTime:String= "00:00";
  saturdayEndTime:String= "00:00";
  sundayStartTime:String= "00:00";
  sundayEndTime:String= "00:00";
  status:String;
 weekId: Number;
 comments:String;
  user:any;
  supervisor:any;
  dateSubmitted:any;
  monTotalHrs;
  tueTotalHrs;
  wedTotalHrs;
  thursTotalHrs;
  friTotalHrs;
  satTotalHrs;
  sunTotalHrs;
  monExtraHrs:String= "00:00";
  tueExtraHrs:String= "00:00";
  wedExtraHrs:String= "00:00";
  thursExtraHrs:String= "00:00";
  friExtraHrs:String= "00:00";
  satExtraHrs:String= "00:00";
  sunExtraHrs:String= "00:00";
  totalHrs;
}
